In [1]:
import pandas as pd

comunas = {14166:'Cerrillos', 14156:'Cerro Navia', 14127:'Conchalí', 16165:'El Bosque', 14157:'Estación Central', 14158:'Huechuraba', 13167:'Independencia', 16110:'La Cisterna', 15128:'La Florida',  16131:'La Granja', 16154:'La Pintana', 15132:'La Reina', 15108:'Las Condes',  15161:'Lo Barnechea', 16164:'Lo Espejo', 14155:'Lo Prado', 15151:'Macul', 14109:'Maipú', 15105:'Ñuñoa', 16162:'Pedro Aguirre Cerda', 15152:'Peñalolén', 15103:'Providencia', 14111:'Pudahuel', 16301:'Puente Alto',  14114:'Quilicura', 14107:'Quinta Normal', 13159:'Recoleta', 14113:'Renca', 16401:'San Bernardo', 16163:'San Joaquín',  16106:'San Miguel', 16153:'San Ramón', 13101:'Santiago',  15160:'Vitacura'} #tiene que ser las comunas de gran santiago

destinos = {'A':'Agrícola', 'B':'Agroindustrial', 'C':'Comercio', 'D':'Deporte y Recreación', 'E':'Educación y Cultura', 'F':'Forestal', 'G':'Hotel, Motel', 'H':'Habitacional', 'I':'Industria', 'L':'Bodega y Almacenaje', 'M':'Minería', 'O':'Oficina', 'P':'Administración Pública y Defensa', 'Q':'Culto', 'S':'Salud', 'T':'Transporte y Telecomunicaciones', 'V':'Otros no considerados', 'W':'Sitio Eriazo', 'Y':'Gallineros, chancheras y otros', 'Z':'Estacionamiento'}

calidad = {1:'Superior', 2:'Media Superior', 3:'Media', 4:'Media Inferior', 5:'Inferior'}

materiales = {'GA': 'Acero', 'GB': 'Hormigón Armado', 'GC': 'Albañilería', 'GE': 'Madera', 'GL': 'Madera Laminada', 'GF': 'Adobe', 'OA': 'Acero', 'OB': 'Hormigón Armado', 'OE': 'Madera', 'SA': 'Silo de Acero', 'SB': 'Silo de Hormigón Armado', 'EA': 'Estanque de Acero', 'EB': 'Estanque de Hormigón Armado', 'M': 'Marquesina', 'P': 'Pavimento', 'W': 'Piscina', 'TA': 'Techumbre Apoyada de Acero', 'TE': 'Techumbre Apoyada de Madera', 'TL': 'Techumbre Apoyada de Madera Laminada', 'A': 'Acero A en tubos y perfiles', 'B': 'Hormigón armado', 'C': 'Albañilería de ladrillo de arcilla, piedra, bloque de cemento u hormigón celular', 'E': 'Madera', 'F': 'Adobe', 'G': 'Perfiles metálicos', 'K': 'Estructura con elementos prefabricados e industrializados'
}

print('Comunas: '+str(comunas)+'\nDestinos: '+str(destinos)+'\nCalidad: '+str(calidad)+'\nMateriales: '+str(materiales))

Comunas: {14166: 'Cerrillos', 14156: 'Cerro Navia', 14127: 'Conchalí', 16165: 'El Bosque', 14157: 'Estación Central', 14158: 'Huechuraba', 13167: 'Independencia', 16110: 'La Cisterna', 15128: 'La Florida', 16131: 'La Granja', 16154: 'La Pintana', 15132: 'La Reina', 15108: 'Las Condes', 15161: 'Lo Barnechea', 16164: 'Lo Espejo', 14155: 'Lo Prado', 15151: 'Macul', 14109: 'Maipú', 15105: 'Ñuñoa', 16162: 'Pedro Aguirre Cerda', 15152: 'Peñalolén', 15103: 'Providencia', 14111: 'Pudahuel', 16301: 'Puente Alto', 14114: 'Quilicura', 14107: 'Quinta Normal', 13159: 'Recoleta', 14113: 'Renca', 16401: 'San Bernardo', 16163: 'San Joaquín', 16106: 'San Miguel', 16153: 'San Ramón', 13101: 'Santiago', 15160: 'Vitacura'}
Destinos: {'A': 'Agrícola', 'B': 'Agroindustrial', 'C': 'Comercio', 'D': 'Deporte y Recreación', 'E': 'Educación y Cultura', 'F': 'Forestal', 'G': 'Hotel, Motel', 'H': 'Habitacional', 'I': 'Industria', 'L': 'Bodega y Almacenaje', 'M': 'Minería', 'O': 'Oficina', 'P': 'Administración Pública y Defensa', 'Q': 'Culto', 'S': 'Salud', 'T': 'Transporte y Telecomunicaciones', 'V': 'Otros no considerados', 'W': 'Sitio Eriazo', 'Y': 'Gallineros, chancheras y otros', 'Z': 'Estacionamiento'}
Calidad: {1: 'Superior', 2: 'Media Superior', 3: 'Media', 4: 'Media Inferior', 5: 'Inferior'}
Materiales: {'GA': 'Acero', 'GB': 'Hormigón Armado', 'GC': 'Albañilería', 'GE': 'Madera', 'GL': 'Madera Laminada', 'GF': 'Adobe', 'OA': 'Acero', 'OB': 'Hormigón Armado', 'OE': 'Madera', 'SA': 'Silo de Acero', 'SB': 'Silo de Hormigón Armado', 'EA': 'Estanque de Acero', 'EB': 'Estanque de Hormigón Armado', 'M': 'Marquesina', 'P': 'Pavimento', 'W': 'Piscina', 'TA': 'Techumbre Apoyada de Acero', 'TE': 'Techumbre Apoyada de Madera', 'TL': 'Techumbre Apoyada de Madera Laminada', 'A': 'Acero A en tubos y perfiles', 'B': 'Hormigón armado', 'C': 'Albañilería de ladrillo de arcilla, piedra, bloque de cemento u hormigón celular', 'E': 'Madera', 'F': 'Adobe', 'G': 'Perfiles metálicos', 'K': 'Estructura con elementos prefabricados e industrializados'}

In [2]:
df_N = pd.read_csv('BRORGA2441N_NAC_2023_2.csv', sep = '|', encoding='ISO-8859-1')

df_N.columns = ['Código Comuna', 'Número de Manzana', 'Número de Predial', 'Dirección o nombre del predio', 'Avalúo fiscal total', 'Contribución semestral (con aseo)', 'Código de destino principal', 'Avalúo exento de la propiedad', 'Código SII de la Comuna Rol Bien Común 1', 'Número de Manzana Rol Bien Común 1', 'Número de predio Rol Bien Común 1', 'Código SII de la Comuna Rol Bien Común 2', 'Número de Manzana Rol Bien Común 2', 'Número de predio Rol Bien Común 2', 'Superficie total del terreno de la propiedad (sin decimales, en m2)']

df_N

,Código Comuna,Número de Manzana,Número de Predial,Dirección o nombre del predio,Avalúo fiscal total,Contribución semestral (con aseo),Código de destino principal,Avalúo exento de la propiedad,Código SII de la Comuna Rol Bien Común 1,Número de Manzana Rol Bien Común 1,Número de predio Rol Bien Común 1,Código SII de la Comuna Rol Bien Común 2,Número de Manzana Rol Bien Común 2,Número de predio Rol Bien Común 2,"Superficie total del terreno de la propiedad (sin decimales, en m2)"
0,1101,1,5,M LIRA 315,140818898,0,O,140818898,0,0,0,0,0,0,566
1,1101,1,6,M LIRA 315,39537563,0,O,39537563,0,0,0,0,0,0,126
2,1101,1,8,M LIRA S/N TERMINAL PESQUERO,1934907470,10322732,C,0,0,0,0,0,0,0,8025
3,1101,1,10,MAXIMO LIRA 389,830168525,4428950,O,0,0,0,0,0,0,0,1588
4,1101,1,12,TERMINAL PESQUERO,56253026,0,C,56253026,0,0,0,0,0,0,211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8019049,16404,5087,27,G MARTINEZ V 217,15257408,0,H,15257408,0,0,0,0,0,0,78
8019050,16404,5087,28,G MARTINEZ V 221,15257408,0,H,15257408,0,0,0,0,0,0,78
8019051,16404,5087,29,G MARTINEZ V 225,15257408,0,H,15257408,0,0,0,0,0,0,78
8019052,16404,5087,30,G MARTINEZ V 229,16800599,0,H,16800599,0,0,0,0,0,0,120
8019053,16404,90160,6,ESTACION PAINE,1292859838,0,T,1292859838,0,0,0,0,0,0,98055

In [3]:
df_N = df_N[df_N['Código Comuna'].isin(comunas.keys())]
# 5, 6, 8 ,9 y del 10 al 14
df_N = df_N.drop(df_N.columns[8:14], axis=1)

df_N.insert(0, 'Cod', df_N.apply(lambda row: str(row['Código Comuna']) + '-' + str(row['Número de Manzana']), axis=1))
df_N.insert(1, 'Rol', df_N.apply(lambda row: str(row['Número de Manzana']) + '-' + str(row['Número de Predial']), axis=1))

df_N

,Cod,Rol,Código Comuna,Número de Manzana,Número de Predial,Dirección o nombre del predio,Avalúo fiscal total,Contribución semestral (con aseo),Código de destino principal,Avalúo exento de la propiedad,"Superficie total del terreno de la propiedad (sin decimales, en m2)"
4521033,13101-1,1-1,13101,1,1,ALAMEDA LIB. B. OHIGGINS 3 LC 1,115804932,617820,C,0,0
4521034,13101-1,1-2,13101,1,2,ALAMEDA LIB. B. OHIGGINS 9,56246553,300078,C,0,0
4521035,13101-1,1-3,13101,1,3,ALAMEDA LIB. B. OHIGGINS 15,57962736,302872,C,0,0
4521036,13101-1,1-4,13101,1,4,ALAMEDA LIB. B. OHIGGINS 75,86491403,461432,C,0,0
4521037,13101-1,1-5,13101,1,5,ALAMEDA LIB. B. OHIGGINS 77,193681656,1033292,C,0,0
...,...,...,...,...,...,...,...,...,...,...,...
7956548,16401-8012,8012-2,16401,8012,2,DIAGONAL LA VARA 01391,26434828,0,H,26434828,80
7956549,16401-8012,8012-3,16401,8012,3,AV DIAGONAL LA VARA 01387,32281172,0,H,32281172,124
7956550,16401-8012,8012-4,16401,8012,4,DIAGOLAL LA VARA 01371,33946270,0,H,33946270,134
7956551,16401-8012,8012-5,16401,8012,5,DIAGONAL LA VARA 01353,26732790,0,H,26732790,81
7956552,16401-8012,8012-6,16401,8012,6,DIAGONAL LA VARA 01345,35167342,0,H,35167342,159

In [4]:
df_N.insert(5, 'Comuna', df_N['Código Comuna'].map(comunas))
df_N.insert(7, 'Destino Principal', df_N['Código de destino principal'].map(destinos))

df_N = df_N.drop(['Código de destino principal', 'Número de Manzana', 'Número de Predial'], axis=1)


df_N

,Cod,Rol,Código Comuna,Comuna,Dirección o nombre del predio,Destino Principal,Avalúo fiscal total,Contribución semestral (con aseo),Avalúo exento de la propiedad,"Superficie total del terreno de la propiedad (sin decimales, en m2)"
4521033,13101-1,1-1,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 3 LC 1,Comercio,115804932,617820,0,0
4521034,13101-1,1-2,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 9,Comercio,56246553,300078,0,0
4521035,13101-1,1-3,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 15,Comercio,57962736,302872,0,0
4521036,13101-1,1-4,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 75,Comercio,86491403,461432,0,0
4521037,13101-1,1-5,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 77,Comercio,193681656,1033292,0,0
...,...,...,...,...,...,...,...,...,...,...
7956548,16401-8012,8012-2,16401,San Bernardo,DIAGONAL LA VARA 01391,Habitacional,26434828,0,26434828,80
7956549,16401-8012,8012-3,16401,San Bernardo,AV DIAGONAL LA VARA 01387,Habitacional,32281172,0,32281172,124
7956550,16401-8012,8012-4,16401,San Bernardo,DIAGOLAL LA VARA 01371,Habitacional,33946270,0,33946270,134
7956551,16401-8012,8012-5,16401,San Bernardo,DIAGONAL LA VARA 01353,Habitacional,26732790,0,26732790,81
7956552,16401-8012,8012-6,16401,San Bernardo,DIAGONAL LA VARA 01345,Habitacional,35167342,0,35167342,159

NL

Cargar el csv y colocar nombre a las columnas

In [5]:
df_NL = pd.read_csv('BRORGA2441NL_NAC_2023_2.csv', sep = '|')

df_NL.columns = ['Código Comuna', 'Número de Manzana', 'Número de Predial', 'Número correlativo de la línea de construcción', 'Código del material estructural de la línea de construcción', 'Código de calidad de la línea de construcción', 'Año de la línea de construcción', 'Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)', 'Código de destino de la línea de construcción', 'Código de condición especial de la línea de construcción']

df_NL

,Código Comuna,Número de Manzana,Número de Predial,Número correlativo de la línea de construcción,Código del material estructural de la línea de construcción,Código de calidad de la línea de construcción,Año de la línea de construcción,"Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)",Código de destino de la línea de construcción,Código de condición especial de la línea de construcción
0,1101,1,4,2,E,3,1925,201,O,NaN
1,1101,1,4,3,C,3,1925,91,O,NaN
2,1101,1,5,1,B,4,1925,213,O,NaN
3,1101,1,5,2,GB,2,1925,13,V,NaN
4,1101,1,6,1,B,4,1925,69,O,NaN
...,...,...,...,...,...,...,...,...,...,...
10441245,16404,90160,6,2,GC,2,1950,520,L,NaN
10441246,16404,90160,6,3,GC,2,1962,240,V,NaN
10441247,16404,90160,6,4,C,4,1962,25,T,NaN
10441248,16404,90160,6,5,E,4,1962,12,V,NaN
10441249,16404,90160,6,6,C,4,2002,59,V,NaN

Dejar las comunas de la gran santiago y colocar el número de rol y manzana con predial

In [6]:
df_NL = df_NL[df_NL['Código Comuna'].isin(comunas.keys())]

df_NL.insert(0, 'Cod', df_NL.apply(lambda row: str(row['Código Comuna']) + '-' + str(row['Número de Manzana']), axis=1))
df_NL.insert(1, 'Rol', df_NL.apply(lambda row: str(row['Número de Manzana']) + '-' + str(row['Número de Predial']), axis=1))

df_NL

,Cod,Rol,Código Comuna,Número de Manzana,Número de Predial,Número correlativo de la línea de construcción,Código del material estructural de la línea de construcción,Código de calidad de la línea de construcción,Año de la línea de construcción,"Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)",Código de destino de la línea de construcción,Código de condición especial de la línea de construcción
5763450,13101-1,1-1,13101,1,1,1,B,3,1955,64,C,NaN
5763451,13101-1,1-1,13101,1,1,2,B,3,1955,54,C,NaN
5763452,13101-1,1-1,13101,1,1,3,B,3,1955,64,C,SB
5763453,13101-1,1-2,13101,1,2,1,B,3,1955,32,C,NaN
5763454,13101-1,1-2,13101,1,2,2,B,3,1955,32,O,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
10358380,16401-8012,8012-2,16401,8012,2,1,C,4,2000,50,H,NaN
10358381,16401-8012,8012-3,16401,8012,3,1,C,4,2000,50,H,NaN
10358382,16401-8012,8012-4,16401,8012,4,1,C,4,2000,50,H,NaN
10358383,16401-8012,8012-5,16401,8012,5,1,C,4,2001,50,H,NaN
10358384,16401-8012,8012-6,16401,8012,6,1,C,4,2000,50,H,NaN

In [7]:
df_NL.insert(2, 'Comuna', df_NL['Código Comuna'].map(comunas))
df_NL.insert(3, 'Destino de la línea de Construcción', df_NL['Código de destino de la línea de construcción'].map(destinos))
df_NL.insert(4, 'Material Estructural', df_NL['Código del material estructural de la línea de construcción'].map(materiales))
df_NL.insert(5, 'Calidad', df_NL['Código de calidad de la línea de construcción'].map(calidad))

df_NL = df_NL.drop(['Código Comuna', 'Código de destino de la línea de construcción', 'Número de Manzana', 'Número de Predial', 'Código del material estructural de la línea de construcción', 'Código de calidad de la línea de construcción', 'Código de condición especial de la línea de construcción', 'Número correlativo de la línea de construcción'], axis=1)

df_NL

,Cod,Rol,Comuna,Destino de la línea de Construcción,Material Estructural,Calidad,Año de la línea de construcción,"Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)"
5763450,13101-1,1-1,Santiago,Comercio,NaN,Media,1955,64
5763451,13101-1,1-1,Santiago,Comercio,NaN,Media,1955,54
5763452,13101-1,1-1,Santiago,Comercio,NaN,Media,1955,64
5763453,13101-1,1-2,Santiago,Comercio,NaN,Media,1955,32
5763454,13101-1,1-2,Santiago,Oficina,NaN,Media,1955,32
...,...,...,...,...,...,...,...,...
10358380,16401-8012,8012-2,San Bernardo,Habitacional,NaN,Media Inferior,2000,50
10358381,16401-8012,8012-3,San Bernardo,Habitacional,NaN,Media Inferior,2000,50
10358382,16401-8012,8012-4,San Bernardo,Habitacional,NaN,Media Inferior,2000,50
10358383,16401-8012,8012-5,San Bernardo,Habitacional,NaN,Media Inferior,2001,50
10358384,16401-8012,8012-6,San Bernardo,Habitacional,NaN,Media Inferior,2000,50

Combinación de ambas base de datos

In [8]:
df_BD = pd.merge(df_N, df_NL, on=['Cod', 'Rol'])
df_BD

,Cod,Rol,Código Comuna,Comuna_x,Dirección o nombre del predio,Destino Principal,Avalúo fiscal total,Contribución semestral (con aseo),Avalúo exento de la propiedad,"Superficie total del terreno de la propiedad (sin decimales, en m2)",Comuna_y,Destino de la línea de Construcción,Material Estructural,Calidad,Año de la línea de construcción,"Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)"
0,13101-1,1-1,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 3 LC 1,Comercio,115804932,617820,0,0,Santiago,Comercio,NaN,Media,1955,64
1,13101-1,1-1,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 3 LC 1,Comercio,115804932,617820,0,0,Santiago,Comercio,NaN,Media,1955,54
2,13101-1,1-1,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 3 LC 1,Comercio,115804932,617820,0,0,Santiago,Comercio,NaN,Media,1955,64
3,13101-1,1-2,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 9,Comercio,56246553,300078,0,0,Santiago,Comercio,NaN,Media,1955,32
4,13101-1,1-2,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 9,Comercio,56246553,300078,0,0,Santiago,Oficina,NaN,Media,1955,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4070174,16401-8012,8012-2,16401,San Bernardo,DIAGONAL LA VARA 01391,Habitacional,26434828,0,26434828,80,San Bernardo,Habitacional,NaN,Media Inferior,2000,50
4070175,16401-8012,8012-3,16401,San Bernardo,AV DIAGONAL LA VARA 01387,Habitacional,32281172,0,32281172,124,San Bernardo,Habitacional,NaN,Media Inferior,2000,50
4070176,16401-8012,8012-4,16401,San Bernardo,DIAGOLAL LA VARA 01371,Habitacional,33946270,0,33946270,134,San Bernardo,Habitacional,NaN,Media Inferior,2000,50
4070177,16401-8012,8012-5,16401,San Bernardo,DIAGONAL LA VARA 01353,Habitacional,26732790,0,26732790,81,San Bernardo,Habitacional,NaN,Media Inferior,2001,50
4070178,16401-8012,8012-6,16401,San Bernardo,DIAGONAL LA VARA 01345,Habitacional,35167342,0,35167342,159,San Bernardo,Habitacional,NaN,Media Inferior,2000,50

In [9]:
df_BD.drop(['Comuna_y', 'Destino de la línea de Construcción'], axis=1, inplace=True)

df_BD.rename(columns={'Comuna_x': 'Comuna'}, inplace=True)

df_BD.fillna('-', inplace=True)

df_BD

,Cod,Rol,Código Comuna,Comuna,Dirección o nombre del predio,Destino Principal,Avalúo fiscal total,Contribución semestral (con aseo),Avalúo exento de la propiedad,"Superficie total del terreno de la propiedad (sin decimales, en m2)",Material Estructural,Calidad,Año de la línea de construcción,"Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)"
0,13101-1,1-1,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 3 LC 1,Comercio,115804932,617820,0,0,-,Media,1955,64
1,13101-1,1-1,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 3 LC 1,Comercio,115804932,617820,0,0,-,Media,1955,54
2,13101-1,1-1,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 3 LC 1,Comercio,115804932,617820,0,0,-,Media,1955,64
3,13101-1,1-2,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 9,Comercio,56246553,300078,0,0,-,Media,1955,32
4,13101-1,1-2,13101,Santiago,ALAMEDA LIB. B. OHIGGINS 9,Comercio,56246553,300078,0,0,-,Media,1955,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4070174,16401-8012,8012-2,16401,San Bernardo,DIAGONAL LA VARA 01391,Habitacional,26434828,0,26434828,80,-,Media Inferior,2000,50
4070175,16401-8012,8012-3,16401,San Bernardo,AV DIAGONAL LA VARA 01387,Habitacional,32281172,0,32281172,124,-,Media Inferior,2000,50
4070176,16401-8012,8012-4,16401,San Bernardo,DIAGOLAL LA VARA 01371,Habitacional,33946270,0,33946270,134,-,Media Inferior,2000,50
4070177,16401-8012,8012-5,16401,San Bernardo,DIAGONAL LA VARA 01353,Habitacional,26732790,0,26732790,81,-,Media Inferior,2001,50
4070178,16401-8012,8012-6,16401,San Bernardo,DIAGONAL LA VARA 01345,Habitacional,35167342,0,35167342,159,-,Media Inferior,2000,50

In [10]:
df_BD = df_BD.groupby("Rol").agg({
    "Cod": "first",
    "Comuna": "first",
    "Código Comuna": "first",
    "Dirección o nombre del predio": "first",
    "Destino Principal": lambda x:', '.join(set(x)),
    "Avalúo fiscal total": "sum",
    "Contribución semestral (con aseo)": "sum",
    "Avalúo exento de la propiedad": "sum",
    "Superficie total del terreno de la propiedad (sin decimales, en m2)": "sum",
    "Material Estructural": lambda x:', '.join(set(x)),
    "Calidad": lambda x:', '.join(set(x)),
    "Año de la línea de construcción": "first",
    "Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)": "sum",
}).reset_index()

df_BD.to_csv('Data.csv', index=False)

df_BD

,Rol,Cod,Comuna,Código Comuna,Dirección o nombre del predio,Destino Principal,Avalúo fiscal total,Contribución semestral (con aseo),Avalúo exento de la propiedad,"Superficie total del terreno de la propiedad (sin decimales, en m2)",Material Estructural,Calidad,Año de la línea de construcción,"Superficie de la línea de construcción (sin decimales, en m2 o m3 según tipo de construcción)"
0,1-1,13101-1,Santiago,13101,ALAMEDA LIB. B. OHIGGINS 3 LC 1,"Comercio, Transporte y Telecomunicaciones, Adm...",94228657778,48093112,84755677015,763889,"-, Acero, Madera","Media Superior, Media Inferior, Superior, Medi...",1955,13800
1,1-10,13101-1,Santiago,13101,MERCED 22 DP 302,"Comercio, Habitacional, Bodega y Almacenaje, O...",39370543210,203621994,1133521103,208047,"-, Acero, Hormigón Armado","Superior, Media Inferior, Media",1955,6076
2,1-100,13101-1,Santiago,13101,MERCED 32 91,Habitacional,177734611,0,177734611,0,-,"Media Inferior, Media",1969,271
3,1-101,13101-1,Santiago,13101,MERCED 32 92,Habitacional,201243004,104914,182426564,0,-,"Media Inferior, Media",1969,301
4,1-102,13101-1,Santiago,13101,MERCED 32 93,Habitacional,223354607,90028,207872104,0,-,"Media Inferior, Media",1969,330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816714,999-95,16401-999,San Bernardo,16401,MARIA GRAHAM 899 B 19 DP 33,Habitacional,15880218,0,15880218,0,-,Media Inferior,1992,39
1816715,999-96,16401-999,San Bernardo,16401,MARIA GRAHAM 899 B 19 DP 34,Habitacional,15880218,0,15880218,0,-,Media Inferior,1992,39
1816716,999-97,16401-999,San Bernardo,16401,MARIA GRAHAM 913 B 20 DP 11,Habitacional,15880218,0,15880218,0,-,Media Inferior,1992,39
1816717,999-98,16401-999,San Bernardo,16401,MARIA GRAHAM 913 B 20 DP 12,Habitacional,15880218,0,15880218,0,-,Media Inferior,1992,39
1816718,999-99,16401-999,San Bernardo,16401,MARIA GRAHAM 913 B 20 DP 13,Habitacional,15880218,0,15880218,0,-,Media Inferior,1992,39